### PR TITLE
feat: bundle databases with package

### LINKED ISSUE #39: Publish `osv-offline` with bundled databases
Make use of npm's `prePublishOnly` scripts to publish to the npm registry with a copy of the OSV databases. That way, they can be used as a fallback of last resort if there are network connectivity issues, GitHub rate limiting, or for use in an airgapped environment.

### PR DESCRIPTION
**Pull request by JamieMagee**
Closes #39

This is hard to test without running `semantic-release` locally, but when running the prepack script manually the databases are included in the `dist` directory:

```sh
$ ls packages/osv-offline/dist/
db  index.d.ts  index.js  lib


$ ls packages/osv-offline/dist/db/
crates.io.nedb  go.nedb  maven.nedb  npm.nedb  nuget.nedb  pypi.nedb  rubygems.nedb
```

### CODE REVIEW

**Comment by JamieMagee** [comment]
@Churro I'd appreciate your review here too :smile:

**Review by viceice — CHANGES_REQUESTED** [review]
If we bundle the database, we always need a new renovate release to get latest db.
this is the same issue like we currently have with the azure pipeline tasks.

I'll add a new idea to the issue

**Comment by JamieMagee** [comment]
That's not the intention of this change. The bundled database is designed to be a fallback if we're unable to download the latest database. For example if the GitHub API is down, or there are other network issues, we can fallback to a stale version of the database. It might not be the most up-to-date, but it is better than nothing.

**Comment by Churro** [comment]
I appreciate the idea, as it adds resilience to download errors due to rate limiting or unavailability. 

However, I'm not yet enirely it will work as intended:

- `osv-offline.zip` gets added whenever osv-offline is bundled
- The database is not re-fetched if modified within <= 24h:
 https://github.com/renovatebot/osv-offline/blob/b7b6a27be022cf39aad2432b3e28e635be1c75cc/packages/osv-offline/src/lib/download.ts#L32
- Now the promise `await new Octokit().repos.listReleases` may be rejected, e.g. to value `[HttpError: Not Found]`:
 https://github.com/renovatebot/osv-offline/blob/b7b6a27be022cf39aad2432b3e28e635be1c75cc/packages/osv-offline/src/lib/download.ts#L37-L41
- ... which will make `osvOffline` fail as well:
https://github.com/renovatebot/osv-offline/blob/b7b6a27be022cf39aad2432b3e28e635be1c75cc/packages/osv-offline/src/lib/osv-offline.ts#L14-L17

Please correct me if I'm overlooking something here.

**Comment by viceice** [comment]
ok, but it'll also blow up a lot. so we should weight that too.

@rarkins WDYT?

**Comment by rarkins** [comment]
I use Renovate as a dependency downstream so would prefer to avoid any major increase in install size.

**Comment by JamieMagee** [comment]
It would add ~7MB to the install size.

**Comment by rarkins** [comment]
Really seems too much. Can you publish two packages - slim and full and Renovate uses the slim?

**Comment by JamieMagee** [comment]
No worries, I'll just close this instead.

**Pull request closed without merging**
